name: Deploy to IONOS

on:
  push:
    branches: [main]
  workflow_dispatch:  # Manueller Deploy-Trigger im GitHub UI

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install lftp
        run: sudo apt-get install -y lftp

      - name: Deploy via FTP to IONOS
        run: |
          lftp -c "
            set ftp:ssl-force true;
            set ftp:ssl-protect-data true;
            set ssl:verify-certificate false;
            open -u '${{ secrets.FTP_USERNAME }}','${{ secrets.FTP_PASSWORD }}' ftps://${{ secrets.FTP_SERVER }};
            mirror --reverse --delete --no-perms --no-umask --parallel=4 ./public/ ${{ secrets.FTP_SERVER_DIR }};
            bye
          "
